### ISSUE TITLE
Support Sketch 52 or 53 plugin update system

### ISSUE THREAD

**Issue by undeadinu** [Carlosarturo28/Appalette#4]
Thank you for building this great plugin. 
I tried it, but no colored object is appeared.  There's just group component. Can you update the plugin or can I do anything?

**Comment by bart** [comment]
Push

**Comment by Carlosarturo28** [comment]
Sorry guys for this very very very late response, but I was fully working on other topics. Now I'll move this plugin to work with Figma and won't update the Sketch version anymore. Please feel free to fork it and make it yours.
